dataset_name: 'in1kcocov2'
dataset_root_path: '../../data/lpcv'
df_train: 'lpcv_in1k_coco_mix_filtered.csv'
df_trainval: 'lpcv_in1k_coco_mix_filtered.csv'
df_val: 'lpcv_test_samples.csv'
df_test: 'lpcv_test_samples.csv'
folder_train: 'images'
folder_val: 'lpcv_test_samples'
folder_test: 'lpcv_test_samples'
df_classid_classname: 'imagenet1k_lpcv_classname_subset.csv'
