dataset_name: 'in1klpcv'
dataset_root_path: '../../data/imagenet1k/ILSVRC/Data/CLS-LOC'
df_train: 'in1klpcv_train.csv'
df_trainval: 'in1klpcv_train.csv'
df_val: 'in1klpcv_val.csv'
df_test: 'in1klpcv_val.csv'
folder_train: 'lpcv_subset_resized'
folder_val: 'lpcv_subset_resized'
folder_test: 'lpcv_subset_resized'
df_classid_classname: 'imagenet1k_lpcv_classname_subset.csv'
