dataset_name: 'in1klpcvv2'
dataset_root_path: '../../data/imagenet1k/ILSVRC/Data/CLS-LOC'
df_train: 'imagenet1k_lpcv_subset.csv'
df_trainval: 'imagenet1k_lpcv_subset.csv'
df_val: 'lpcv_sample.csv'
df_test: 'lpcv_sample.csv'
folder_train: 'lpcv_subset_resized'
folder_val: 'lpcv_test_samples'
folder_test: 'lpcv_test_samples'
df_classid_classname: 'imagenet1k_lpcv_classname_subset.csv'
