dataset_name: 'in1k'
dataset_root_path: '../../data/imagenet1k/ILSVRC/Data/CLS-LOC'
df_train: 'train.csv'
df_trainval: train_val.csv
df_val: 'val.csv'
df_test: 'test.csv'
folder_train: 'train'
folder_val: 'train'
folder_test: 'val'
df_classid_classname: 'classid_classname.csv'
