dataset_name: 'mixallv2eval'
dataset_root_path: '../../data/lpcv'
df_train: 'lpcv_in1k_coco_syn_mix_parsed_filtered.csv'
df_trainval: 'lpcv_in1k_coco_syn_mix_parsed_filtered.csv'
df_val: 'sample_v2.csv'
df_test: 'sample_v2.csv'
folder_train: 'images'
folder_val: 'images'
folder_test: 'images'
df_classid_classname: 'imagenet1k_lpcv_classname_subset.csv'
