dataset_name: 'mixfinalsingle'
dataset_root_path: '../../data/lpcv'
df_train: 'lpcv_in1k_cocosingle_syn_mix_parsed_all.csv'
df_trainval: 'lpcv_in1k_cocosingle_syn_mix_parsed_all.csv'
df_val: 'sample_v3.csv'
df_test: 'sample_v3.csv'
folder_train: 'images'
folder_val: 'images'
folder_test: 'images'
df_classid_classname: 'imagenet1k_lpcv_classname_subset.csv'
