dataset_name: 'mscocolpcv'
dataset_root_path: 'data/mscocolpcv'
df_train: 'coco_lpcv_subset.csv'
df_trainval: 'coco_lpcv_subset.csv'
df_val: 'lpcv_sample.csv'
df_test: 'lpcv_sample.csv'
folder_train: 'images'
folder_val: 'lpcv_test_samples'
folder_test: 'lpcv_test_samples'
df_classid_classname: 'imagenet1k_lpcv_classname_subset.csv'
