dataset_name: 'mscocolpcvfinal'
dataset_root_path: '../../data/lpcv'
df_train: 'mscoco_lpcv_subset_all.csv'
df_trainval: 'mscoco_lpcv_subset_all.csv'
df_val: 'sample_v3.csv'
df_test: 'sample_v3.csv'
folder_train: 'images'
folder_val: 'images'
folder_test: 'images'
df_classid_classname: 'imagenet1k_lpcv_classname_subset.csv'
